name: Update README with Latest Resume

on:
  push:
    branches: [ main, master ]
    paths:
      - '*.pdf'
      - 'Dhruv_s_resume*.pdf'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Find latest resume
      id: find-resume
      run: |
        # Find all resume PDFs and sort by filename (which contains date)
        latest_resume=$(ls -1 Dhruv_s_resume*.pdf 2>/dev/null | sort -V | tail -1)
        
        if [ -z "$latest_resume" ]; then
          echo "No resume files found!"
          exit 1
        fi
        
        echo "Latest resume: $latest_resume"
        echo "latest_resume=$latest_resume" >> $GITHUB_OUTPUT
        
        # Extract date from filename for display
        if [[ $latest_resume =~ Dhruv_s_resume___([0-9]{2})_([0-9]{2})_([0-9]{2})\.pdf ]]; then
          year="20${BASH_REMATCH[3]}"
          month="${BASH_REMATCH[2]}"
          day="${BASH_REMATCH[1]}"
          echo "Resume date: $year-$month-$day"
          echo "resume_date=$year-$month-$day" >> $GITHUB_OUTPUT
        fi
    
    - name: Update README
      run: |
        latest_resume="${{ steps.find-resume.outputs.latest_resume }}"
        resume_date="${{ steps.find-resume.outputs.resume_date }}"
        
        # Get the repository owner and name from GitHub context
        repo_owner="${{ github.repository_owner }}"
        repo_name="${{ github.event.repository.name }}"
        
        # Create the new download link
        new_link="https://github.com/$repo_owner/$repo_name/raw/main/$latest_resume"
        
        # Update README.md with the new link
        sed -i "s|https://github\.com/[^/]*/[^/]*/raw/main/Dhruv_s_resume[^\"]*\.pdf|$new_link|g" README.md
        
        echo "Updated README.md with latest resume: $latest_resume"
        echo "Download link: $new_link"
        
        # Check if README was actually modified
        if git diff --quiet README.md; then
          echo "No changes needed to README.md"
          echo "readme_changed=false" >> $GITHUB_ENV
        else
          echo "README.md has been updated"
          echo "readme_changed=true" >> $GITHUB_ENV
          git diff README.md
        fi
    
    - name: Commit and push changes
      if: env.readme_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "🤖 Auto-update README with latest resume: ${{ steps.find-resume.outputs.latest_resume }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create summary
      run: |
        latest_resume="${{ steps.find-resume.outputs.latest_resume }}"
        resume_date="${{ steps.find-resume.outputs.resume_date }}"
        
        echo "## 📄 Resume Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Latest Resume:** \`$latest_resume\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Resume Date:** $resume_date" >> $GITHUB_STEP_SUMMARY
        echo "- **README Updated:** ${{ env.readme_changed }}" >> $GITHUB_STEP_SUMMARY 